#! /bin/sh

[ -f $HOME/.xprofile ] && . $HOME/.xprofile
[ -f $HOME/.config/screenlayout/dual.sh ] && . $HOME/.config/screenlayout/dual.sh

xrdb $HOME/.Xresources
xsetroot -cursor_name left_ptr &

export PATH=$PATH:$HOME/.local/bin

bash $HOME/.config/polybar/launch.sh --grayblocks &
dwall -s market

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

bspc monitor DP-1 -d I II III
bspc monitor HDMI-2 -d IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_follows_monitor false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
